Repository hapinessjs/hapiness, pull requests merged in 2018-03, with the labels that each got.

#77 feat(socket): store
  package.json
  src/extensions/socket-server/socket.ts
  test/integration/socket-server-rooms.test.ts
Labels: enhancement

#78 release(version): v1.3.2
  package.json
  src/extensions/socket-server/socket.ts
  test/integration/socket-server-rooms.test.ts
Labels: enhancement

#80 TDW-7540 Some enhancements
  API.md
  README.md
  package-lock.json
  package.json
  src/core/enums.ts
  src/core/hapiness.ts
  src/core/interfaces/extension.ts
  src/core/interfaces/hapiness.ts
  src/core/interfaces/index.ts
  src/core/shutdown.ts
  src/extensions/http-server/extension.ts
  src/extensions/socket-server/extension.ts
  src/extensions/socket-server/server.ts
  src/index.ts
  test/integration/core.test.ts
  test/integration/socket-server-http-server-ext.test.ts
  test/unit/hapiness.test.ts
  test/unit/shutdown.test.ts
Labels: dependencies, documentation, enhancement

#81 release(version): v1.4.0
  API.md
  README.md
  package-lock.json
  package.json
  src/core/enums.ts
  src/core/hapiness.ts
  src/core/interfaces/extension.ts
  src/core/interfaces/hapiness.ts
  src/core/interfaces/index.ts
  src/core/shutdown.ts
  src/extensions/http-server/extension.ts
  src/extensions/socket-server/extension.ts
  src/extensions/socket-server/server.ts
  src/index.ts
  test/integration/core.test.ts
  test/integration/socket-server-http-server-ext.test.ts
  test/unit/hapiness.test.ts
  test/unit/shutdown.test.ts
Labels: dependencies, documentation, enhancement

#82 Update README.md
  README.md
Labels: documentation

#83 feat(event-manager): new extension
  API.md
  README.md
  package.json
  src/extensions/event-manager/README.md
  src/extensions/event-manager/extension.ts
  src/extensions/event-manager/index.ts
  src/extensions/event-manager/manager.ts
  src/extensions/event-manager/service.ts
  src/extensions/socket-server/extension.ts
  src/index.ts
  test/integration/event-manager.test.ts
Labels: documentation, enhancement
